### ISSUE TITLE
sandardize

### ISSUE THREAD

**Issue by ericpgreen** [ASKurz/recoding-Hayes-2018#4]
In 2.4 you probably meant to call this function `standardize()`. Of course it works as `sandardize()`, but you refer to it in the text as `standardize()`.

<img width="798" alt="Screen Shot 2021-09-18 at 4 50 36 PM" src="https://user-images.githubusercontent.com/546433/133908206-e3332620-e1d0-4d80-a6ef-b13b85050bbe.png">

**Comment by ASKurz** [comment]
:man_facepalming: Well that's embarrassing. Thanks for the catch!
